volumes:
  n8n_storage:
  postgres_storage:
  qdrant_storage:
  ollama_storage:

networks:
  syncbricks:

x-n8n: &service-n8n
  image: n8nio/n8n:1.97.1
  networks: ['syncbricks']
  environment:
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=postgres
    - DB_POSTGRESDB_USER=${your_user_name}
    - DB_POSTGRESDB_PASSWORD=${your_password}
    - DB_POSTGRESDB_DATABASE=n8ndb
    - N8N_DIAGNOSTICS_ENABLED=false
    - N8N_PERSONALIZATION_ENABLED=false
    - N8N_ENCRYPTION_KEY=${your_key}
    - N8N_USER_MANAGEMENT_JWT_SECRET=${your_secret}
    - WEBHOOK_URL=http://localhost:5678/
    - GENERIC_TIMEZONE=Asia/Kolkata
  depends_on:
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:16-alpine
    networks: ['syncbricks']
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${your_user_name}
      - POSTGRES_PASSWORD=${your_password}
      - POSTGRES_DB=n8ndb
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${your_user_name} -d n8ndb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "5433:5432"

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    networks: ['syncbricks']
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  ollama:
    image: ollama/ollama
    container_name: ollama
    networks: ['syncbricks']
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_storage:/root/.ollama

  n8n-import:
    <<: *service-n8n
    container_name: n8n-import
    restart: "no"
    entrypoint: /bin/sh
    command:
      - "-c"
      - |
        echo "Waiting for database to be ready..."
        while ! nc -z postgres 5432; do
          sleep 1
        done
        echo "Database is ready. Starting import..."
        n8n import:credentials --separate --input=/backup/credentials || true
        n8n import:workflow --separate --input=/backup/workflows || true
        touch /home/node/.n8n/import_done
        exit 0
    volumes:
      - ./n8n/backup:/backup
      - n8n_storage:/home/node/.n8n

  n8n:
    <<: *service-n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - n8n_storage:/home/node/.n8n
      - ./n8n/backup:/backup
      - ./shared:/data/shared
    depends_on:
      postgres:
        condition: service_healthy
      n8n-import:
        condition: service_completed_successfully
    entrypoint: /bin/sh
    command:
      - "-c"
      - |
        echo 'Waiting for dependencies...'
        while ! nc -z postgres 5432 || [ ! -f /home/node/.n8n/import_done ]; do
          sleep 1
        done
        echo 'Dependencies are ready. Starting n8n...'
        sleep 5
        n8n
